myCtStanFit <- function(sim_data) {
    ctfit <- ctStanFit(
        datalong = sim_data,
        ctstanmodel = ctmodel,
        cores = ctsem_cores,
        optimize = TRUE,
        fit = FALSE,
        saveCompile = TRUE,
        verbose = 0,
        priors = FALSE
      )
      
      # Run optimization manually
      optres <- ctsem:::stanoptimis(
        standata = ctfit$standata,
        sm = sm,
        init = NULL,
        tol = 1e-7,
        matsetup = data.frame(ctfit$ctstanmodel$modelmats$matsetup),
        verbose = 0, 
        stochastic = FALSE,
        priors = FALSE,
        cores = ctfit$args$cores
      )
      
      # Rebuild the fit object
      fitobj <- rebuild_ctfit_from_manual(ctfit, optres)

  
  return(fitobj)
  
}

safe_fit <- purrr::safely(myCtStanFit, otherwise = NULL)

#' Fit a continuous-time model to one simulated dataset
#'
#' @description
#' Fits a previously defined \code{ctsem} continuous-time structural
#' equation model to a single simulated dataset, using an internal safe
#' wrapper around Stan optimization. The function returns a one-row tibble
#' summarizing the estimated population mean and 95% credible interval of
#' the key parameter \code{gamma_r1}.  If model fitting fails, it returns
#' placeholder values with \code{ok = FALSE}.
#'
#' @param sim_data
#' A tibble or data frame containing one simulated dataset in long format,
#' typically generated by \code{\link{simulate_ct_data}()}.  Must include
#' columns \code{id}, \code{time}, observed variables (e.g. \code{Y1–Y4}),
#' and the time-dependent covariate \code{TD1}.
#'
#' @details
#' Internally, \code{fit_once()} calls a helper function
#' \code{safe_fit()}, which wraps \code{myCtStanFit()} in
#' \code{purrr::safely()} to catch optimization errors. The
#' \code{ctStanFit()} object is created and optimized via
#' \code{ctsem:::stanoptimis()}, then rebuilt using
#' \code{rebuild_ctfit_from_manual()}.The function extracts the
#' population-level summary from the fitted object and isolates the row
#' corresponding to the parameter \code{gamma_r1}.
#'
#' @return
#' A tibble with one row and four columns:
#' \describe{
#'   \item{ok}{Logical; \code{TRUE} if fitting succeeded, \code{FALSE} otherwise.}
#'   \item{est}{Posterior mean estimate of \code{gamma_r1}.}
#'   \item{l95}{Lower bound of the 95\% credible interval.}
#'   \item{u95}{Upper bound of the 95\% credible interval.}
#' }
#'
#' @examples
#' sim_data <- simulate_ct_data(n_subjects = 20, Tpoints = 60, seed = 1)
#' fit_once(sim_data)
#'
#' @seealso
#' \code{\link{simulate_ct_data}}, \code{\link{ctStanFit}},
#' \code{\link{rebuild_ctfit_from_manual}}
#'
#' @export
fit_once <- function(sim_data) {

  fit <- safe_fit(sim_data)
  
  if (!is.null(fit$error)) {
    print(fit$error)
    return(tibble(ok = FALSE, est = NA, l95 = NA, u95 = NA))
  }
  
  
  summ <- summary(fit$result)$popmeans |> as_tibble(rownames = "parameter")
  
  #gamma_row <- summ |> filter(parameter == "gamma_r1")
  gamma_row <- summ |> filter(parameter == "eff_L_inter")
  
  tibble(
    ok = TRUE,
    est = gamma_row$mean,
    l95 = gamma_row$`2.5%`,
    u95 = gamma_row$`97.5%`
  )
}


fit_both_models <- function(sim_data) {
  total_planned_obs <- nrow(sim_data)
  actual_missings <- sum(is.na(sim_data$load1))
  prop_missing <- actual_missings / total_planned_obs
  
  
  results <- list()
  
  df_lmm <- sim_data |>
    group_by(id) |>
    mutate(
      load_avg = (load1 + load2) / 2,
      agency_avg = (agency1 + agency2) / 2,
      dt = c(NA, diff(time)),
      lag_agency = lag(agency_avg),
      lag_load = lag(load_avg),
      lag_trigger = lag(mrt_trigger) #
    ) |>
    mutate(
      agency_cmc = mean(agency_avg, na.rm = TRUE), 
      agency_cwc = agency_avg - agency_cmc,          
      lag_agency_cwc = lag_agency - agency_cmc,
      load_cmc = mean(load_avg, na.rm = TRUE), 
      load_cwc = load_avg - load_cmc,          
      lag_load_cwc = lag_load - load_cmc,
    ) |>
    ungroup() |>
    filter(!is.na(lag_load_cwc), !is.na(dt))
  
  fit_lme <- purrr::safely(nlme::lme)(
    fixed = load_avg ~ lag_load_cwc * lag_trigger + # Verzögerte Interaktion
      lag_load_cwc * mrt_trigger + # Aktuelle Interaktion
      lag_agency_cwc + load_cmc + agency_cmc + dt,
    random = ~ 1 | id,
    correlation = nlme::corCAR1(form = ~ time | id),
    data = df_lmm,
    na.action = na.exclude,
    method = "ML",
    control = nlme::lmeControl(opt = "optim", maxIter = 100)
  )
  
  
  if (!is.null(fit_lme$error)) {
    res_lmm <- tibble(model = "nlme_lme", ok = FALSE, est = NA, l95 = NA, u95 = NA, n_obs = NA)
  } else {
    # Extraktion der Interaktion: lag_load_cwc:mrt_trigger
    # Das entspricht der Logik: Wirkt der Trigger stärker bei hohem Stress (cwc)?
    summ_lme <- summary(fit_lme$result)$tTable
    row_name <- "lag_load_cwc:lag_trigger"
    n_used_lme <- fit_lme$result$dims$N
    if (row_name %in% rownames(summ_lme)) {
      est_val <- summ_lme[row_name, "Value"]
      se_val  <- summ_lme[row_name, "Std.Error"]
      res_lmm <- tibble(
        model = "nlme_lme", ok = TRUE, est = est_val,
        l95 = est_val - 1.96 * se_val, u95 = est_val + 1.96 * se_val,
        n_obs = n_used_lme
      )
    } else {
      res_lmm <- tibble(model = "nlme_lme", ok = FALSE, est = NA, l95 = NA, u95 = NA, n_obs = NA)
    }
  }
  
  #  CTSEM
  fit_ctsem <- safe_fit(sim_data)
  
  
  if (!is.null(fit_ctsem$error)) {
    res_ctsem <- tibble(model = "ctsem", ok = FALSE, est = NA, l95 = NA, u95 = NA, n_obs = NA)
  } else {
    summ <- summary(fit_ctsem$result)$popmeans %>% as.data.frame() %>% tibble::rownames_to_column("parameter")
    gamma_row <- summ %>% filter(parameter == "eff_L_inter")
    n_used_ctsem <- total_planned_obs 
    
    res_ctsem <- tibble(
      model = "ctsem", ok = TRUE, est = gamma_row$mean,
      l95 = gamma_row$`2.5%`, u95 = gamma_row$`97.5%`,
      n_obs = n_used_ctsem
    )
  }
  
  return(bind_rows(res_lmm, res_ctsem))
}
